name: opencda
channels:
  - defaults
dependencies:
  - pip==21.1.2
  - python==3.7.10
  - pip:
    - matplotlib==3.4.2
    - networkx==2.5.1
    - numpy
    - pillow
    - pyparsing==2.4.7
    - six==1.16.0
    - open3d
    - opencv-python==4.5.2.52
    - pandas
    - pygame
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn
    - lxml
    - coloredlogs
    - grpc_tools
    - jinja2
    - psutil
    - asyncio
    - carla==0.9.12
    - k-means-constrained==0.7.0
    - ortools==9.3.10497
    - grpcio-tools
    - shapely==1.8.4
